# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-sed/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$HOME/bin:$HOME/.cabal/bin:$HOME/.rvm/bin:$HOME/.local/bin:/usr/lib/node_modules/express-generator/bin/:$HOME/.cargo/bin

export EDITOR="nvim"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

set -o vi

alias l='ls -l'
alias ll='ls -lh'
alias la='ll -a'
alias vim='nvim'
alias vi='nvim'
alias ..='cd ..'

export PS1="`whoami` $ "
