execute pathogen#infect()

syntax on
filetype plugin indent on
set background=dark
set modelines=5
set laststatus=2
set relativenumber
set clipboard=unnamed
set mouse=v
set dir=~/.config/vimswap//,/var/tmp//,/tmp//

let mapleader="q"

nnoremap <Leader>f :NERDTree<cr>

nnoremap ^n j
nnoremap ^p k

nnoremap <Leader>el :ElmEvalLine<CR>
vnoremap <Leader>es :<C-u>ElmEvalSelection<CR>
nnoremap <Leader>em :ElmMakeCurrentFile<CR>

set hidden

let g:js_fmt_fail_silently = 1
let g:js_fmt_autosave = 1

let g:racer_cmd = "/Users/bheesham.persaud/.cargo/bin/racer"
let $RUST_SRC_PATH="/usr/local/share/rust/src"
let g:rustfmt_autosave = 1
let g:racer_experimental_completer = 1

